# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PaySDKDemo' do
  
  	pod 'AFNetworking', '3.0.4'
    pod 'YYCategories', '1.0.4'
    pod 'MBProgressHUD+BWMExtension', '1.0.1'
    pod 'DCPaySDK', '~> 1.0.4'

  target 'PaySDKDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PaySDKDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
